### ISSUE TITLE
Filtering with multiple namespaces doesn't work

### ISSUE THREAD

**Issue by utr1903** [utr1903/monitoring-kubernetes-with-opentelemetry#8]
The values below:
```yaml
newrelic:
  someteam:
    endpoint: "otlp.nr-data.net:4317"
    licenseKey: "xxx"
    namespaces:
      - ns1
      - ns2
```

generates the following config:
```yaml
filter/someteam:
  error_mode: ignore
  metrics:
    datapoint:
      - 'attributes["namespace"] != "ns1"'
      - 'attributes["namespace"] != "ns2"'
```

which represents an `and` case for 2 different negative impressions. Therefore, the processor filters every metric out instead of keeping only these 2 namespaces.
