### ISSUE TITLE
Fix yaml for global config in docs

### ISSUE THREAD

**Issue by utr1903** [utr1903/monitoring-kubernetes-with-opentelemetry#82]
The `enabled` and `endpoint` attributes should be within the `newrelic` attribute:
```
global:
  newrelic:
    enabled: true
    endpoint: "OTLP_ENDPOINT_FOR_ALL_ACCOUNTS"
    ...
```
